### ISSUE TITLE
No way to declare multiple named taxonomies for inclusion in term meta plugins

### ISSUE THREAD

**Issue by dustyf** [johnjamesjacoby/wp-term-meta-ui#1]
I am running into an issue where I want to use the Term Color plugin on two taxonomies, but no others.  It would be nice to be able to use an array of taxonomy names that would work in this case, but it currently is impossible.  The get_taxonomies function accepts a name argument, however it does not accept an array of names here allowing you only to limit this to one named taxonomy.  https://github.com/johnjamesjacoby/wp-term-meta-ui/blob/master/class-wp-term-meta-ui.php#L207

It would be nice if there was another filter in place that would allow us to filter the return value of that method instead of just the arguments being passed to the get_taxonomies function.

 I will submit a pull request shortly.

**Comment by JJJ** [comment]
Try:

```
add_filter( 'wp_term_color_get_taxonomies', function( $args = array() ) {
    return array(
        'show_ui' => true,
        'colors'  => true
    );
} );
```

Then, you can add the `colors` property to the taxonomies you want to use them on, either via manipulating the global. If these are custom taxonomies, you can pass the `colors` property into its registration array.
